# configs/params.yaml

train_params:
  test_size: 0.2
  random_state: 42
  experiment_name: "Model Monitoring Project"

linear_model:
  name: "linear-regression-model"
  grid_search:
    fit_intercept: [True, False]
    copy_X: [True, False]

pytorch_model:
  name: "pytorch-model"
  hyperparameters:
    epochs: [10, 20]
    learning_rate: [0.01, 0.001]